In [10]:
#Simple Linear Regression example to predict the first year college grades of students from their high school SAT and GPA scores

#Prodigy University is seeking to enhance its enrollment process. They plan to do so by implementing a predictive analytics model aimed at identifying prospective students who demonstrate a high potential for academic success.

#The goal is to develop a predictive model that can accurately forecast the first-year college GPA of applicants based on their SAT scores and high school scores. This model is intended to serve as a strategic tool for the admissions office, enabling them to efficiently shortlist candidates who not only meet the academic standards of the university but are also likely to thrive in their chosen fields of study. By doing so, the university aspires to optimize its student selection process, improve academic outcomes, and foster an environment of excellence and high achievement.

In [11]:
import pandas as pd

In [12]:
df=pd.read_csv('student_gpa_data_1000.csv')
df.head(5)

sat_sum  hs_gpa  fy_gpa
0      482    3.54    3.53
1      728    2.56    3.50
2      650    3.70    3.94
3      486    3.44    3.81
4      451    2.62    2.31

In [13]:
from collections.abc import ValuesView
# convert data to numpy
X = data[['sat_sum','hs_gpa']].values
# reshape the fy_gpa into 2D array with [data size] rows and 1 column
y=data['fy_gpa'].values.reshape(-1,1)
print(X.shape)
print(y.shape)

(1000, 2)
(1000, 1)


In [14]:
# train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
from sklearn.preprocessing import StandardScaler
# normalize the feautures so that it is easier to train the data
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [16]:
X_train.shape

(800, 2)

In [17]:
import torch
# convert numpy to Pytorch tensors
X_train_tensor=torch.tensor(X_train,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train,dtype=torch.float32)
X_test_tensor=torch.tensor(X_test,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test,dtype=torch.float32)


In [18]:
# BUILDING MODEL

import torch.nn as nn


In [19]:
# BUILDING MODEL WITH 2 NEURONS
model=nn.Sequential(
    nn.Linear(2,2), # 2 i/p 2 o/p
    nn.Sigmoid(),   # activation fxn
    nn.Linear(2,1)
)

In [20]:
# forward propagation
preds=model(X_train_tensor)

In [21]:
preds[:5]

tensor([[-0.3924],
        [-0.2920],
        [-0.3729],
        [-0.1692],
        [-0.5185]], grad_fn=<SliceBackward0>)

In [22]:
from torch.nn import MSELoss

In [23]:
# Calculating Loss
criterion = MSELoss()
loss=criterion(preds, y_train_tensor)
print(loss)


tensor(14.1217, grad_fn=<MseLossBackward0>)


In [24]:
preds[:5]

tensor([[-0.3924],
        [-0.2920],
        [-0.3729],
        [-0.1692],
        [-0.5185]], grad_fn=<SliceBackward0>)

In [25]:
y_train_tensor[:5]

tensor([[3.4500],
        [2.3300],
        [3.2100],
        [3.8600],
        [3.6400]])

In [26]:
model[0].weight

Parameter containing:
tensor([[ 0.6534,  0.0514],
        [-0.6183, -0.1389]], requires_grad=True)

In [27]:
model[2].weight

Parameter containing:
tensor([[-0.6579,  0.1126]], requires_grad=True)

In [28]:

import torch.optim as optim
# Your optimizer
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [29]:
loss.backward()

In [30]:
optimizer.step()

In [31]:
model[0].weight

Parameter containing:
tensor([[ 0.6535,  0.0513],
        [-0.6183, -0.1388]], requires_grad=True)

In [32]:
model[2].weight

Parameter containing:
tensor([[-0.6533,  0.1163]], requires_grad=True)

In [33]:
from torch.utils.data import TensorDataset,DataLoader

In [34]:
train_data=TensorDataset(X_train_tensor,y_train_tensor)

In [35]:
train_data=TensorDataset(X_train_tensor,y_train_tensor)

In [36]:
model=nn.Sequential(
    nn.Linear(2,2),
    nn.Sigmoid(),
    nn.Linear(2,1)
)
optimizer=optim.SGD(model.parameters(),lr=0.001)

In [37]:
# performance on train and test sets before training
train_loss = criterion(model(X_train_tensor),y_train_tensor).item()
test_loss = criterion(model(X_test_tensor),y_test_tensor).item()
print(f' without Training:\n Train Loss: {train_loss:.4f}, Test Loss: {test_loss:.4f}')


 without Training:
 Train Loss: 6.0057, Test Loss: 6.1519


In [38]:
#  looking at predictions
model(X_train_tensor)[:5]

tensor([[0.9391],
        [0.9022],
        [0.9645],
        [0.9017],
        [0.9903]], grad_fn=<SliceBackward0>)

In [39]:
# STOCHASTIC GRADIENT DESCENT
train_loader=DataLoader(train_data,batch_size=1,shuffle=True)
for epoch in range(10):
  for x_batch,y_batch in train_loader:
    # forward pass
    preds=model(x_batch)
    loss=criterion(preds,y_batch)
    # backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  train_loss=criterion(model(X_train_tensor),y_train_tensor).item()
  # print epoch,': ',train_loss)
  test_loss = criterion(model(X_test_tensor), y_test_tensor).item()
  print(f'Epoch {epoch+1}: Train Loss: {train_loss:.4f}, Test Loss: {test_loss:.4f}')

Epoch 1: Train Loss: 0.1571, Test Loss: 0.1678
Epoch 2: Train Loss: 0.0933, Test Loss: 0.0911
Epoch 3: Train Loss: 0.0868, Test Loss: 0.0856
Epoch 4: Train Loss: 0.0828, Test Loss: 0.0818
Epoch 5: Train Loss: 0.0803, Test Loss: 0.0804
Epoch 6: Train Loss: 0.0790, Test Loss: 0.0787
Epoch 7: Train Loss: 0.0779, Test Loss: 0.0794
Epoch 8: Train Loss: 0.0774, Test Loss: 0.0797
Epoch 9: Train Loss: 0.0769, Test Loss: 0.0784
Epoch 10: Train Loss: 0.0767, Test Loss: 0.0782


In [40]:
#looking at predictions
model(X_train_tensor)[:5]

tensor([[3.3029],
        [3.0389],
        [3.5147],
        [3.0512],
        [3.6575]], grad_fn=<SliceBackward0>)

In [41]:
# reintialize model weights
model=nn.Sequential(
    nn.Linear(2,2),
    nn.Sigmoid(),
    nn.Linear(2,1)
)
optimizer=optim.SGD(model.parameters(),lr=0.001)

In [42]:
train_loader=DataLoader(train_data,batch_size=800,shuffle=True)
for epoch in range(1000):
  for x_batch,y_batch in train_loader:
    # forward pass
    preds=model(x_batch)
    loss=criterion(preds,y_batch)
    # backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  if (epoch+1)%100==0:
    train_loss=criterion(model(X_train_tensor),y_train_tensor).item()
    # print epoch,': ',train_loss)
    test_loss = criterion(model(X_test_tensor), y_test_tensor).item()
    print(f'Epoch {epoch+1}: Train Loss: {train_loss:.4f}, Test Loss: {test_loss:.4f}')

Epoch 100: Train Loss: 5.1687, Test Loss: 5.3018
Epoch 200: Train Loss: 2.7399, Test Loss: 2.8273
Epoch 300: Train Loss: 1.4811, Test Loss: 1.5337
Epoch 400: Train Loss: 0.8454, Test Loss: 0.8726
Epoch 500: Train Loss: 0.5289, Test Loss: 0.5382
Epoch 600: Train Loss: 0.3709, Test Loss: 0.3681
Epoch 700: Train Loss: 0.2903, Test Loss: 0.2794
Epoch 800: Train Loss: 0.2468, Test Loss: 0.2308
Epoch 900: Train Loss: 0.2213, Test Loss: 0.2021
Epoch 1000: Train Loss: 0.2046, Test Loss: 0.1836


In [43]:
# mini batch gradient descent
model=nn.Sequential(
    nn.Linear(2,2),
    nn.Sigmoid(),
    nn.Linear(2,1)
)
optimizer=optim.SGD(model.parameters(),lr=0.001)

In [44]:
train_loader=DataLoader(train_data,batch_size=64,shuffle=True)
for epoch in range(500):
  for x_batch,y_batch in train_loader:
    # forward pass
    preds=model(x_batch)
    loss=criterion(preds,y_batch)
    # backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  if (epoch+1)%50==0:
    train_loss=criterion(model(X_train_tensor),y_train_tensor).item()
    # print epoch,': ',train_loss)
    test_loss = criterion(model(X_test_tensor), y_test_tensor).item()
    print(f'Epoch {epoch+1}: Train Loss: {train_loss:.4f}, Test Loss: {test_loss:.4f}')

Epoch 50: Train Loss: 0.4767, Test Loss: 0.5253
Epoch 100: Train Loss: 0.2858, Test Loss: 0.3154
Epoch 150: Train Loss: 0.2299, Test Loss: 0.2529
Epoch 200: Train Loss: 0.1901, Test Loss: 0.2089
Epoch 250: Train Loss: 0.1603, Test Loss: 0.1758
Epoch 300: Train Loss: 0.1379, Test Loss: 0.1508
Epoch 350: Train Loss: 0.1211, Test Loss: 0.1320
Epoch 400: Train Loss: 0.1086, Test Loss: 0.1179
Epoch 450: Train Loss: 0.0993, Test Loss: 0.1073
Epoch 500: Train Loss: 0.0925, Test Loss: 0.0994


In [45]:
# GRADIENT DESCENT WITH MOMENTUM

In [46]:

model=nn.Sequential(
    nn.Linear(2,2),
    nn.Sigmoid(),
    nn.Linear(2,1)
)
optimizer=optim.SGD(model.parameters(),lr=0.001,momentum=0.9)

In [47]:
train_loader=DataLoader(train_data,batch_size=64,shuffle=True)
for epoch in range(500):
  for x_batch,y_batch in train_loader:
    # forward pass
    preds=model(x_batch)
    loss=criterion(preds,y_batch)
    # backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  if (epoch+1)%50==0:
    train_loss=criterion(model(X_train_tensor),y_train_tensor).item()
    # print epoch,': ',train_loss)
    test_loss = criterion(model(X_test_tensor), y_test_tensor).item()
    print(f'Epoch {epoch+1}: Train Loss: {train_loss:.4f}, Test Loss: {test_loss:.4f}')

Epoch 50: Train Loss: 0.1431, Test Loss: 0.1428
Epoch 100: Train Loss: 0.0902, Test Loss: 0.0915
Epoch 150: Train Loss: 0.0806, Test Loss: 0.0830
Epoch 200: Train Loss: 0.0789, Test Loss: 0.0817
Epoch 250: Train Loss: 0.0782, Test Loss: 0.0814
Epoch 300: Train Loss: 0.0776, Test Loss: 0.0810
Epoch 350: Train Loss: 0.0772, Test Loss: 0.0805
Epoch 400: Train Loss: 0.0768, Test Loss: 0.0802
Epoch 450: Train Loss: 0.0765, Test Loss: 0.0798
Epoch 500: Train Loss: 0.0762, Test Loss: 0.0797


In [49]:
# NESTERON MOMENTUM
model=nn.Sequential(
    nn.Linear(2,2),
    nn.Sigmoid(),
    nn.Linear(2,1)
)
optimizer=optim.SGD(model.parameters(),lr=0.001,momentum=0.9,nesterov=True)

In [50]:
train_loader=DataLoader(train_data,batch_size=64,shuffle=True)
for epoch in range(500):
  for x_batch,y_batch in train_loader:
    # forward pass
    preds=model(x_batch)
    loss=criterion(preds,y_batch)
    # backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  if (epoch+1)%50==0:
    train_loss=criterion(model(X_train_tensor),y_train_tensor).item()
    # print epoch,': ',train_loss)
    test_loss = criterion(model(X_test_tensor), y_test_tensor).item()
    print(f'Epoch {epoch+1}: Train Loss: {train_loss:.4f}, Test Loss: {test_loss:.4f}')


Epoch 50: Train Loss: 0.1352, Test Loss: 0.1434
Epoch 100: Train Loss: 0.0855, Test Loss: 0.0903
Epoch 150: Train Loss: 0.0780, Test Loss: 0.0817
Epoch 200: Train Loss: 0.0770, Test Loss: 0.0805
Epoch 250: Train Loss: 0.0766, Test Loss: 0.0801
Epoch 300: Train Loss: 0.0763, Test Loss: 0.0797
Epoch 350: Train Loss: 0.0760, Test Loss: 0.0795
Epoch 400: Train Loss: 0.0758, Test Loss: 0.0793
Epoch 450: Train Loss: 0.0756, Test Loss: 0.0791
Epoch 500: Train Loss: 0.0754, Test Loss: 0.0789


In [51]:
# ADAGRAD
# NESTERON MOMENTUM
model=nn.Sequential(
    nn.Linear(2,2),
    nn.Sigmoid(),
    nn.Linear(2,1)
)
optimizer=optim.Adagrad(model.parameters())


In [52]:
train_loader=DataLoader(train_data,batch_size=64,shuffle=True)
for epoch in range(500):
  for x_batch,y_batch in train_loader:
    # forward pass
    preds=model(x_batch)
    loss=criterion(preds,y_batch)
    # backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  if (epoch+1)%50==0:
    train_loss=criterion(model(X_train_tensor),y_train_tensor).item()
    # print epoch,': ',train_loss)
    test_loss = criterion(model(X_test_tensor), y_test_tensor).item()
    print(f'Epoch {epoch+1}: Train Loss: {train_loss:.4f}, Test Loss: {test_loss:.4f}')


Epoch 50: Train Loss: 4.1973, Test Loss: 4.3184
Epoch 100: Train Loss: 2.6579, Test Loss: 2.7555
Epoch 150: Train Loss: 1.7438, Test Loss: 1.8234
Epoch 200: Train Loss: 1.1635, Test Loss: 1.2282
Epoch 250: Train Loss: 0.7882, Test Loss: 0.8407
Epoch 300: Train Loss: 0.5441, Test Loss: 0.5867
Epoch 350: Train Loss: 0.3852, Test Loss: 0.4198
Epoch 400: Train Loss: 0.2815, Test Loss: 0.3097
Epoch 450: Train Loss: 0.2136, Test Loss: 0.2369
Epoch 500: Train Loss: 0.1690, Test Loss: 0.1883


In [53]:
# RMS PROP
model=nn.Sequential(
    nn.Linear(2,2),
    nn.Sigmoid(),
    nn.Linear(2,1)
)
optimizer=optim.RMSprop(model.parameters())


In [54]:
train_loader=DataLoader(train_data,batch_size=64,shuffle=True)
for epoch in range(500):
  for x_batch,y_batch in train_loader:
    # forward pass
    preds=model(x_batch)
    loss=criterion(preds,y_batch)
    # backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  if (epoch+1)%50==0:
    train_loss=criterion(model(X_train_tensor),y_train_tensor).item()
    # print epoch,': ',train_loss)
    test_loss = criterion(model(X_test_tensor), y_test_tensor).item()
    print(f'Epoch {epoch+1}: Train Loss: {train_loss:.4f}, Test Loss: {test_loss:.4f}')


Epoch 50: Train Loss: 0.0740, Test Loss: 0.0763
Epoch 100: Train Loss: 0.0737, Test Loss: 0.0762
Epoch 150: Train Loss: 0.0742, Test Loss: 0.0761
Epoch 200: Train Loss: 0.0758, Test Loss: 0.0754
Epoch 250: Train Loss: 0.0737, Test Loss: 0.0782
Epoch 300: Train Loss: 0.0743, Test Loss: 0.0756
Epoch 350: Train Loss: 0.0746, Test Loss: 0.0797
Epoch 400: Train Loss: 0.0737, Test Loss: 0.0777
Epoch 450: Train Loss: 0.0749, Test Loss: 0.0758
Epoch 500: Train Loss: 0.0743, Test Loss: 0.0787


In [55]:
 # ADAM
 model=nn.Sequential(
    nn.Linear(2,2),
    nn.Sigmoid(),
    nn.Linear(2,1)
)
optimizer=optim.Adam(model.parameters())

In [56]:
train_loader=DataLoader(train_data,batch_size=64,shuffle=True)
for epoch in range(500):
  for x_batch,y_batch in train_loader:
    # forward pass
    preds=model(x_batch)
    loss=criterion(preds,y_batch)
    # backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  if (epoch+1)%50==0:
    train_loss=criterion(model(X_train_tensor),y_train_tensor).item()
    # print epoch,': ',train_loss)
    test_loss = criterion(model(X_test_tensor), y_test_tensor).item()
    print(f'Epoch {epoch+1}: Train Loss: {train_loss:.4f}, Test Loss: {test_loss:.4f}')


Epoch 50: Train Loss: 5.9391, Test Loss: 6.0827
Epoch 100: Train Loss: 1.2983, Test Loss: 1.3626
Epoch 150: Train Loss: 0.1680, Test Loss: 0.1862
Epoch 200: Train Loss: 0.0789, Test Loss: 0.0845
Epoch 250: Train Loss: 0.0760, Test Loss: 0.0796
Epoch 300: Train Loss: 0.0757, Test Loss: 0.0793
Epoch 350: Train Loss: 0.0754, Test Loss: 0.0789
Epoch 400: Train Loss: 0.0750, Test Loss: 0.0784
Epoch 450: Train Loss: 0.0747, Test Loss: 0.0779
Epoch 500: Train Loss: 0.0744, Test Loss: 0.0776
