In [1]:
import numpy as np
y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

In [9]:
# MEAN ABSOLUTE ERROR
# method 1
def mae(y_predicted,y_true):
    total_error=0
    for yp,yt in zip(y_predicted,y_true):
        total_error+=abs(yp-yt)
    print("Total error is:",total_error)
    mae=total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [10]:
mae(y_true,y_predicted)

Total error is: 2.5
Mean absolute error is: 0.5


np.float64(0.5)

In [11]:
# method 2 by numpy
np.mean(np.abs(y_predicted-y_true))

np.float64(0.5)

In [44]:
# MEAN SQUARE ERROR
# method 1
np.mean((y_predicted - y_true) ** 2)


np.float64(0.366)

In [45]:
# method 2
def mse(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += (yp - yt) ** 2
    print("Total error is:", total_error)
    mse_value = total_error / len(y_predicted)
    print("Mean Squared Error is:", mse_value)
    return mse_value

In [46]:
mse(y_predicted,y_true)

Total error is: 1.83
Mean Squared Error is: 0.366


np.float64(0.366)

In [16]:
#  LOG LOSS OR BINARY CROSS ENTROPY
# LOG(0)  not define here in python so use number very close to 0 eg 0.00001
# also in formula 1- predicted in multiply so predicted never 0 use epsilon
np.log([0.000000000000000001])

array([-41.44653167])

In [35]:
epsilon = 1e-15

In [36]:
y_predicted # this is original one  but we want all 1s to be near 0.99999

array([1, 1, 0, 0, 1])

In [37]:
 # now covertig all 0s and 1s to near by number
 # for 1
y_predicted_new = [max(float(i), epsilon) for i in y_predicted]

y_predicted_new

[1.0, 1.0, 1e-15, 1e-15, 1.0]

In [38]:
# for log
y_predicted_new = [min(i, 1 - epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [39]:
# combine to get new perfect array
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)



array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [40]:
# formual of log loss
# method 1
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


np.float64(17.2696280766844)

In [41]:
# method 2
def log_loss(y_true,y_predicted):
  epsilon = 1e-15
  y_predicted_new=[max(i,epsilon) for i in y_predicted]
  y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
  y_predicted_new=np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [43]:
log_loss(y_true, y_predicted)

np.float64(17.2696280766844)