In [1]:
import numpy as np

In [2]:
revenue=np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses=np.array([[80,90,100],[10,16,20],[8,10,10]])


In [3]:
profit=revenue-expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [4]:
price_per_unit=np.array([1000,400,1200])
units=np.array([[30,40,50],[5,10,15],[2,5,7]])

In [6]:
# here is broadcasting of matrix that is in b/w expansion of price_per_unit
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

In [7]:
prices_in_indian=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
prices_in_indian
prices_in_dollar=prices_in_indian*75
prices_in_dollar

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [8]:
units_sold=np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit=np.array([20,30,15])
total_sales=np.dot(price_per_unit,units_sold)
total_sales


array([1900, 2640, 1430])