In [1]:
# import the torch libraries followed by torch.nn library as nn
import torch
import torch.nn as nn

In [2]:
# inputs to the neuron random values
inputs=torch.tensor([3.0,2.0,-1.0])

In [7]:
# create a neuron with 3 features and 1 output
neuron=nn.Linear(in_features=3,out_features=1)
output=neuron(inputs)

In [8]:
# print the final o/p of neuron
print(output)

tensor([-0.6788], grad_fn=<ViewBackward0>)


In [9]:
# to view the weight of the neuron
neuron.weight

Parameter containing:
tensor([[-0.3263,  0.2977,  0.3454]], requires_grad=True)

In [10]:
# to view bias of neuron
neuron.bias

Parameter containing:
tensor([0.0501], requires_grad=True)

In [11]:
# verify if mathematical formula works for this
neuron.weight@inputs.T+neuron.bias

/tmp/ipython-input-2463908164.py:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:3725.)
  neuron.weight@inputs.T+neuron.bias


tensor([-0.6788], grad_fn=<AddBackward0>)