In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
import pandas as pd

# Manually creating the dataset
import pandas as pd

data = {
    'age': [
        22, 25, 47, 52, 46, 56, 23, 56, 55, 60,
        34, 31, 29, 48, 41, 53, 30, 45, 38, 27,
        40, 36, 33, 26, 50, 42, 28, 39
    ],
    'affordibility': [
        1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
        1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
        1, 1, 0, 0, 1, 0, 0, 1
    ],
    'bought_insurance': [
        0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
        1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
        1, 1, 0, 0, 1, 0, 0, 1
    ]
}

df = pd.DataFrame(data)
print(df.shape)  # Output: (28, 3)
print(df.head())


(28, 3)
   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=2)

In [ ]:
len(X_train)

22

In [ ]:
df.shape

(28, 3)

In [ ]:
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100
X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

In [ ]:
X_train_scaled # all values from 0 to 1 this is scaling to wok better

age  affordibility
16  0.30              0
6   0.23              0
3   0.52              0
21  0.36              1
26  0.28              0
25  0.42              0
12  0.29              0
4   0.46              1
10  0.34              1
5   0.56              1
20  0.40              1
2   0.47              1
7   0.56              1
24  0.50              1
23  0.26              0
18  0.38              1
11  0.31              0
22  0.33              0
27  0.39              1
13  0.48              1
15  0.53              0
8   0.55              1

In [ ]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,), activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(X_train_scaled,y_train,epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 937ms/step - accuracy: 0.5455 - loss: 0.5160
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.5455 - loss: 0.5157
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5455 - loss: 0.5154
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.5151
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.5148
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5455 - loss: 0.5145
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5455 - loss: 0.5142
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.5139
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5455 - loss: 0.5135
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5455 - loss: 0.5132
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.5129
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5455 - 

In [ ]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - accuracy: 0.8333 - loss: 0.5461


[0.5460723638534546, 0.8333333134651184]

In [ ]:
X_test_scaled

age  affordibility
1   0.25              0
0   0.22              1
14  0.41              1
9   0.60              1
19  0.27              0
17  0.45              1

In [ ]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step


array([[0.42869803],
       [0.76953125],
       [0.78882176],
       [0.8069029 ],
       [0.4315923 ],
       [0.7927288 ]], dtype=float32)

In [ ]:
y_test

1     0
0     0
14    1
9     1
19    0
17    1
Name: bought_insurance, dtype: int64

In [ ]:
# to know final weighs and bias by get weights
coef,intercept=model.get_weights()
coef,intercept

(array([[0.59037876],
        [1.5105425 ]], dtype=float32),
 array([-0.43475989], dtype=float32))

In [ ]:
# same by scratch
def sigmoid(x):
  import math
  return 1/(1+math.exp(-x))
sigmoid(18)

0.9999999847700205

In [ ]:
def prediction_function(age,affordibility):
  weighted_sum=coef[0]*age+coef[1]*affordibility+intercept
  return sigmoid(weighted_sum)

In [ ]:
prediction_function(0.47,1)

0.7946621911085162

In [ ]:
prediction_function(0.18,1)

0.7653163470251746

In [ ]:
# gardient descent method from scratch

def log_loss(y_true,y_predicted):
    epsilon = 1e-15
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [ ]:
def sigmoid_numpy(X):
  return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [ ]:
class myNN:
  def __init__(self):
    self.w1 = 1
    self.w2 = 1
    self.bias = 0
    pass

  def fit(self, X, y, epochs, loss_thresold):
    self.w1, self.w2, self.bias = self.gradient_descent(X['age'], X['affordibility'], y, epochs, loss_thresold)
  def predict(self, X_test):
    weighted_sum = self.w1 * X_test['age'] + self.w2 * X_test['affordibility'] + self.bias
    return sigmoid_numpy(weighted_sum)
  # gradient descent fxn for weights and bias
  def gradient_descent(self, age, affordibility, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)

    for i in range(epochs):
      weighted_sum = w1 * age + w2 * affordibility + bias
      y_predicted = sigmoid_numpy(weighted_sum)

      loss = log_loss(y_true, y_predicted)

      w1d = (1/n) * np.dot(np.transpose(age), (y_predicted - y_true))
      w2d = (1/n) * np.dot(np.transpose(affordibility), (y_predicted - y_true))
      bias_d = np.mean(y_predicted - y_true)

      w1 = w1 - rate * w1d
      w2 = w2 - rate * w2d
      bias = bias - rate * bias_d
      if i%50==0:
        print(f'epoch: {i}, w1: {w1}, w2: {w2}, bias: {bias}, loss: {loss}')

      if loss <= loss_thresold:
        break

    return w1, w2, bias


In [ ]:
customModel=myNN()
customModel.fit(X_train_scaled,y_train,epochs=500,loss_thresold=0.4631)

epoch: 0, w1: 0.9765054212514402, w2: 1.0517187653038091, bias: -0.08138641165535439, loss: 0.5160445543475977


In [ ]:
coef,intercept

(array([[0.59037876],
        [1.5105425 ]], dtype=float32),
 array([-0.43475989], dtype=float32))

In [ ]:
customModel.predict(X_test_scaled)

1     0.469731
0     0.754678
14    0.785096
9     0.812678
19    0.474240
17    0.791138
dtype: float64